AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - "**/db/**/*"
    - "**/bin/*"
    - "app/models/external_origin/namely.rb"
    - "app/services/importing/us_cellular/constants.rb"
    - "app/models/smart_groups/constants.rb"
    - "app/models/smart_groups/operator_collection.rb"

Rails:
  Enabled: true

# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

# Configuration parameters: AlignWith, SupportedStyles.
Lint/DefEndAlignment:
  Enabled: false

# Configuration parameters: AlignWith, SupportedStyles.
Lint/EndAlignment:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: false

# Cop supports --auto-correct.
Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Max: 40
  Severity: refactor

Metrics/BlockNesting:
  Max: 3

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 180
  Severity: refactor

# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 180
  Severity: refactor

Metrics/CyclomaticComplexity:
  Max: 5
  Severity: refactor

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 242

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 20
  Severity: refactor

# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Enabled: false
  Max: 6
  Severity: refactor

Metrics/PerceivedComplexity:
  Max: 5
  Severity: refactor

Style/AccessorMethodName:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle, SupportedLastArgumentHashStyles.
Style/AlignHash:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AlignParameters:
  Enabled: false

Style/AsciiComments:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BarePercentLiterals:
  Enabled: false

# Cop supports --auto-correct.
Style/BlockEndNewline:
  Enabled: false

# Cop supports --auto-correct.
Style/BlockDelimiters:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassAndModuleChildren:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassCheck:
  Enabled: false

Style/ClassVars:
  Enabled: false

# Cop supports --auto-correct.
Style/ColonMethodCall:
  Enabled: false

Style/Documentation:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/DotPosition:
  Enabled: false

Style/EachWithObject:
  Enabled: false

# Cop supports --auto-correct.
Style/ElseAlignment:
  Enabled: false

Style/EmptyElse:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: AllowAdjacentOneLineDefs.
Style/EmptyLineBetweenDefs:
  Enabled: false

# Cop supports --auto-correct.
Style/EmptyLines:
  Enabled: false

# Cop supports --auto-correct.
Style/EmptyLinesAroundAccessModifier:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundBlockBody:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundClassBody:
  Enabled: false

# Cop supports --auto-correct.
Style/EmptyLinesAroundMethodBody:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundModuleBody:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyMethod:
  Enabled: false
  EnforcedStyle: expanded
  SupportedStyles:
    - compact
    - expanded

Style/EndOfLine:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FormatString:
  Enabled: false

# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Enabled: false

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/IndentHash:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Enabled: false

# Cop supports --auto-correct.
Style/Lambda:
  Enabled: false

# Cop supports --auto-correct.
Style/MultilineBlockLayout:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MultilineOperationIndentation:
  Enabled: false

# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
Style/Next:
  Enabled: false

# Cop supports --auto-correct.
Style/NilComparison:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: AllowSafeAssignment.
Style/ParenthesesAroundCondition:
  Enabled: false

# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

# Cop supports --auto-correct.
Style/Proc:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/RaiseArgs:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: false

# Configuration parameters: MaxSlashes.
Style/RegexpLiteral:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: false

# Configuration parameters: Methods.
Style/SingleLineBlockParams:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: AllowIfMethodIsEmpty.
Style/SingleLineMethods:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiteralsInInterpolation:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/TrailingBlankLines:
  Enabled: false

# Cop supports --auto-correct.
Style/TrailingWhitespace:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: ExactNameMatch, AllowPredicates, AllowDSLWriters, Whitelist.
Style/TrivialAccessors:
  Enabled: false

Style/UnlessElse:
  Enabled: false

# Cop supports --auto-correct.
Style/UnneededPercentQ:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: WordRegex.
Style/WordArray:
  MinSize: 4

# Cop supports --auto-correct.
Style/ClosingParenthesisIndentation:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: AllowForAlignment.
Style/ExtraSpacing:
  AllowForAlignment: true

# Cop supports --auto-correct.
# Configuration parameters: MultiSpaceAllowedForOperators.
Style/SpaceAroundOperators:
  Exclude:
    - "config/initializers/database_connection.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Rails/Date:
  EnforcedStyle: flexible
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: Include.
Rails/ReadWriteAttribute:
  Enabled: false

# Configuration parameters: EnforcedStyle, SupportedStyles.
Rails/TimeZone:
  EnforcedStyle: flexible
  Enabled: false

# Configuration parameters: Include.
Rails/Validation:
  Enabled: false

# We currently use `private` to designate private class methods, e.g.
#
# private
#
# def self.some_class_method
#
# `private` does not work like this, and what we're doing is wrong,
# (we should instead be using `private_class_method`)
Lint/IneffectiveAccessModifier:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: prefer_alias, prefer_alias_method
Style/Alias:
  EnforcedStyle: prefer_alias_method

# * Holding off on this pending a decision on
# * https://github.com/lessonly/lessonly.github.io/pull/37
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, IndentationWidth.
# SupportedStyles: aligned, indented
Style/MultilineMethodCallIndentation:
  Enabled: false

# Disables check for method name styling
# Allows for support of Confident Ruby conversion methods
# that start with capital letters
# http://rubocop.readthedocs.io/en/latest/cops_style/#stylemethodname
Style/MethodName:
  Enabled: false
